name: Release new version
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        options:
          - patch
          - minor
          - major
        description: 'Release type (one of): patch, minor, major'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: |
          npm i

      - name: Bump version in package.json
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.release-type }}

      - name: Determine the release version
        run: |
          echo "NEW_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build for CDN and package it up
        run: |
          npm run build
          tar -czvf mfe-dummy-${{ env.NEW_VERSION }}_cdn.tgz -C ./dist .

      - name: Push tags and create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add package.json
          git commit -m "${{ env.NEW_VERSION}}"
          git tag ${{ env.NEW_VERSION }}
          git push --tags
          gh release create ${{ env.NEW_VERSION }} kek-${{ env.NEW_VERSION }}_cdn.tgz --title ${{ env.NEW_VERSION }}
